### ISSUE TITLE
Exception on Win 7

### ISSUE THREAD

**Issue by elena-ungureanu** [mikedouglasdev/changescreenresolution#1]
Hello Mike,

I've been using your application to set the resolution on different VMs - Win 8.1, Win 10 and Win 7. It works on Win 10 and 8.1, but I get an exception on Win 7 as below, even when not passing parameters or with 1024 768 as parameters. I was wondering if you've seen this error or did you had the chance to use this exe on a Win 7 VM?

System.InvalidOperationException: The display driver failed the specified graphics mode. at ChangeScreenResolution.DisplayManager.SetDisplaySettings(DisplaySettings set) at ChangeScreenResolution.Program.Main(String[] args) 

Please let me know,
Elena

**Comment by mikedouglasdev** [comment]
Hi Elena,  sorry for the delay.  did you use the email notification to see the available modes.  Did you happen to chose one that is applicable for that machine?  I haven't seen this error.

**Comment by elena-ungureanu** [comment]
Hi Mike,

I haven’t seen that error in a while.

In a local copy I’ve changed the code a bit and instead sending all information in an email is saved in a log file. Also I’ve increased a bit the number of retries when changing the resolution – please find a sample below.

Overall is a very useful tool, thank you for sharing it.

Kind regards,
Elena

2017-01-20 04:57:05.5273 INFO Start
2017-01-20 04:57:05.5586 INFO Display parameters: width 1600 x height 1200; 5 retries
2017-01-20 04:57:05.5586 INFO Original resolution = 1024 x 768
2017-01-20 04:57:05.5586 INFO Available Modes:
2017-01-20 04:57:05.5586 INFO
mode=640 480
2017-01-20 04:57:05.5586 INFO
mode=800 600
2017-01-20 04:57:05.5586 INFO
mode=1024 768
2017-01-20 04:57:05.5586 INFO
mode=1152 864
2017-01-20 04:57:05.5586 INFO
mode=1280 1024
2017-01-20 04:57:05.5586 INFO
mode=1600 1200
2017-01-20 04:57:05.5586 INFO
mode=640 480
2017-01-20 04:57:05.5586 INFO
mode=800 600
2017-01-20 04:57:05.5742 INFO New resolution = 1600 x 1200

**Comment by mikedouglasdev** [comment]
Thanks for the feedback.  Sounds like we can close this.
